services:
  api:
    build: ./back-end/
    volumes:
      - ./back-end:/app
      - /venv
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://user:password@db:27017/mydatabase

  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongo_data: